INSERT INTO questions (id, level, question) VALUES (1, 1, 'Опиши то, что тебя окружает в твоей желаемой реальности.');
INSERT INTO questions (id, level, question) VALUES (2, 1, 'Где ты просыпаешься каждое утро?');
INSERT INTO questions (id, level, question) VALUES (3, 1, 'Что ты видишь вокруг себя, когда открываешь глаза?');
INSERT INTO questions (id, level, question) VALUES (4, 1, 'Какие звуки наполняют твоё пространство?');
INSERT INTO questions (id, level, question) VALUES (5, 1, 'Какие запахи ты ощущаешь утром и днём?');
INSERT INTO questions (id, level, question) VALUES (6, 1, 'Какие прикосновения, текстуры, ощущения кожи создают комфорт вокруг?');
INSERT INTO questions (id, level, question) VALUES (7, 1, 'Кто находится рядом с тобой в этой жизни?');
INSERT INTO questions (id, level, question) VALUES (8, 1, 'Какие предметы, цвета, формы тебя окружают?');
INSERT INTO questions (id, level, question) VALUES (9, 1, 'Что ты видишь за окном?');
INSERT INTO questions (id, level, question) VALUES (10, 1, 'Какие места ты посещаешь в течение дня?');
INSERT INTO questions (id, level, question) VALUES (11, 1, 'Как выглядит твоё рабочее, творческое или расслабляющее пространство?');
INSERT INTO questions (id, level, question) VALUES (12, 2, 'Расскажи, как проходит твой день в этой реальности.');
INSERT INTO questions (id, level, question) VALUES (13, 2, 'Как проходит твоё утро — с чего ты его начинаешь?');
INSERT INTO questions (id, level, question) VALUES (14, 2, 'Что ты делаешь в течение дня?');
INSERT INTO questions (id, level, question) VALUES (15, 2, 'Как ты проводишь вечер?');
INSERT INTO questions (id, level, question) VALUES (16, 2, 'Какие привычки поддерживают твою энергию и вдохновение?');
INSERT INTO questions (id, level, question) VALUES (17, 2, 'Какие ритуалы делают твой день особенным?');
INSERT INTO questions (id, level, question) VALUES (18, 2, 'Что ты выбираешь делать осознанно?');
INSERT INTO questions (id, level, question) VALUES (19, 2, 'Как ты заботишься о себе в течение дня?');
INSERT INTO questions (id, level, question) VALUES (20, 2, 'Что в твоих действиях приносит тебе удовольствие?');
INSERT INTO questions (id, level, question) VALUES (21, 2, 'С кем ты взаимодействуешь и как это происходит?');
INSERT INTO questions (id, level, question) VALUES (22, 2, 'Что ты делаешь регулярно, что делает твою жизнь яркой?');
INSERT INTO questions (id, level, question) VALUES (23, 3, 'Опиши, что ты умеешь и как это проявляется в твоей жизни.');
INSERT INTO questions (id, level, question) VALUES (24, 3, 'В чём ты уже мастер?');
INSERT INTO questions (id, level, question) VALUES (25, 3, 'Какие таланты проявляются в тебе естественно?');
INSERT INTO questions (id, level, question) VALUES (26, 3, 'Какие новые навыки ты используешь каждый день с лёгкостью?');
INSERT INTO questions (id, level, question) VALUES (27, 3, 'Что у тебя получается особенно легко и радостно?');
INSERT INTO questions (id, level, question) VALUES (28, 3, 'Какие способности помогают тебе создавать твою реальность?');
INSERT INTO questions (id, level, question) VALUES (29, 3, 'Какие качества ты применяешь каждый день?');
INSERT INTO questions (id, level, question) VALUES (30, 3, 'Чем ты делишься с другими?');
INSERT INTO questions (id, level, question) VALUES (31, 3, 'Как ты обучаешь других (или вдохновляешь)?');
INSERT INTO questions (id, level, question) VALUES (32, 3, 'Что тебя отличает в твоих делах?');
INSERT INTO questions (id, level, question) VALUES (33, 3, 'Какие инструменты и подходы ты используешь в своей деятельности?');
INSERT INTO questions (id, level, question) VALUES (34, 4, 'Расскажи, какие идеи и принципы лежат в основе твоей реальности.');
INSERT INTO questions (id, level, question) VALUES (35, 4, 'Во что ты веришь, когда смотришь на свой день?');
INSERT INTO questions (id, level, question) VALUES (36, 4, 'Какие ценности проявляются в твоих действиях?');
INSERT INTO questions (id, level, question) VALUES (37, 4, 'Что для тебя всегда истинно?');
INSERT INTO questions (id, level, question) VALUES (38, 4, 'Какие убеждения поддерживают твою внутреннюю гармонию?');
INSERT INTO questions (id, level, question) VALUES (39, 4, 'Что ты считаешь важным в жизни и в себе?');
INSERT INTO questions (id, level, question) VALUES (40, 4, 'Какие внутренние правила ты создаёшь для себя?');
INSERT INTO questions (id, level, question) VALUES (41, 4, 'Что ты знаешь о себе и о мире в этой реальности?');
INSERT INTO questions (id, level, question) VALUES (42, 4, 'Как ты реагируешь на вызовы, опираясь на свои ценности?');
INSERT INTO questions (id, level, question) VALUES (43, 4, 'Какие убеждения делают твою жизнь лёгкой?');
INSERT INTO questions (id, level, question) VALUES (44, 4, 'Что ты выбираешь чувствовать по отношению к себе и к миру?');
INSERT INTO questions (id, level, question) VALUES (45, 5, 'Опиши, кем ты являешься в своей желаемой жизни.');
INSERT INTO questions (id, level, question) VALUES (46, 5, 'Кто ты в этой реальности?');
INSERT INTO questions (id, level, question) VALUES (47, 5, 'Как ты себя называешь или ощущаешь?');
INSERT INTO questions (id, level, question) VALUES (48, 5, 'Какой образ себя ты воплощаешь каждый день?');
INSERT INTO questions (id, level, question) VALUES (49, 5, 'Какие роли ты играешь с удовольствием и радостью?');
INSERT INTO questions (id, level, question) VALUES (50, 5, 'Что делает тебя уникальным/уникальной?');
INSERT INTO questions (id, level, question) VALUES (51, 5, 'Как ты ощущаешь свою силу и уверенность?');
INSERT INTO questions (id, level, question) VALUES (52, 5, 'Как ты проявляешь свою глубину и суть?');
INSERT INTO questions (id, level, question) VALUES (53, 5, 'Как ты говоришь о себе другим?');
INSERT INTO questions (id, level, question) VALUES (54, 5, 'Какие чувства у тебя вызывает твоя личность?');
INSERT INTO questions (id, level, question) VALUES (55, 5, 'Как ты ощущаешь свою целостность и значимость?');
INSERT INTO questions (id, level, question) VALUES (56, 6, 'Опиши, ради чего ты живёшь, что выше тебя, что соединяет тебя с целым.');
INSERT INTO questions (id, level, question) VALUES (57, 6, 'Ради чего ты живёшь в этой реальности?');
INSERT INTO questions (id, level, question) VALUES (58, 6, 'Как ты ощущаешь своё предназначение?');
INSERT INTO questions (id, level, question) VALUES (59, 6, 'В чём твоя миссия и вклад в мир?');
INSERT INTO questions (id, level, question) VALUES (60, 6, 'Как ты служишь жизни, людям, земле?');
INSERT INTO questions (id, level, question) VALUES (61, 6, 'Как твоя деятельность связана с более высоким смыслом?');
INSERT INTO questions (id, level, question) VALUES (62, 6, 'Как ты ощущаешь свою связь с источником (Богом, Вселенной, духом)?');
INSERT INTO questions (id, level, question) VALUES (63, 6, 'Что ты создаёшь, что остаётся после тебя?');
INSERT INTO questions (id, level, question) VALUES (64, 6, 'Что ты ощущаешь, когда следуешь своему пути?');
INSERT INTO questions (id, level, question) VALUES (65, 6, 'Как ты ощущаешь свою духовную свободу?');
INSERT INTO questions (id, level, question) VALUES (66, 6, 'Что даёт тебе глубокое чувство покоя и доверия?');
